import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import type { BusinessProfile, Sale, Expense } from '../types';
import { format } from 'date-fns';
import { Share } from '@capacitor/share';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { isProductExempt } from './taxLogic';

// Helper to write and share file
const writeAndShare = async (filename: string, base64Data: string) => {
    try {
        const savedFile = await Filesystem.writeFile({
            path: filename,
            data: base64Data,
            directory: Directory.Cache,
            recursive: true
        });

        await Share.share({
            title: 'Tax Insight Report',
            url: savedFile.uri,
            dialogTitle: 'Share Tax Report'
        });
    } catch (e) {
        console.error('Error sharing file:', e);
        throw e;
    }
};

export const shareTaxReportPDF = async (
    taxData: any,
    business: BusinessProfile,
    period: string,
    sales: Sale[],
    expenses: Expense[]
) => {
    const doc = new jsPDF();
    const currency = 'N';

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text("Tax Insight Report (Detailed)", 14, 22);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by DailyProfit • ${format(new Date(), 'PPpp')}`, 14, 28);
    doc.text(`Includes ${sales.length} Sales and ${expenses.length} Expenses`, 14, 33);

    doc.setDrawColor(200, 200, 200);
    doc.line(14, 35, 196, 35);

    // Business Details
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Business: ${business.name}`, 14, 45);
    doc.text(`Period: ${period}`, 14, 51);

    // Summary Table
    autoTable(doc, {
        startY: 58,
        head: [['Metric', 'Amount']],
        body: [
            ['Total Sales', `${currency}${taxData.totalRevenue.toLocaleString()}`],
            ['Total Expenses', `${currency}${taxData.totalExpenses.toLocaleString()}`],
            ['Net Profit', `${currency}${taxData.netProfit.toLocaleString()}`],
            ['Taxable Sales', `${currency}${taxData.taxableSales.toLocaleString()}`],
            ['Exempt Sales', `${currency}${taxData.exemptSales.toLocaleString()}`],
        ],
        theme: 'striped',
        headStyles: { fillColor: [22, 163, 74] }, // Green
    });

    // Tax Estimates
    let finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.text("Estimated Tax Obligations", 14, finalY);

    autoTable(doc, {
        startY: finalY + 5,
        head: [['Tax Type', 'Estimate', 'Note']],
        body: [
            ['VAT (7.5%)', `${currency}${taxData.vatAmount.toLocaleString()}`, taxData.isVatExemptByTurnover ? 'Turnover below threshold' : 'On taxable sales only'],
            [`${taxData.taxType} (Income Based)`, `${currency}${taxData.incomeTaxAmount.toLocaleString()}`, 'Estimated on profit'],
            ['TOTAL ESTIMATE', `${currency}${(taxData.vatAmount + taxData.incomeTaxAmount).toLocaleString()}`, '']
        ],
        theme: 'grid',
        headStyles: { fillColor: [70, 70, 70] },
    });

    // Disclaimer
    finalY = (doc as any).lastAutoTable.finalY + 20;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("DISCLAIMER: This report is a generated estimate for internal planning purposes only.", 14, finalY);
    doc.text("DailyProfit does not provide legal or tax advice. Consult a professional before filing.", 14, finalY + 5);

    // --- DETAILED BREAKDOWN ---
    doc.addPage();
    doc.setFontSize(14);
    doc.setTextColor(40, 40, 40);
    doc.text("Appendix A: Detailed Sales Log", 14, 20);

    // Sort sales by date desc
    const sortedSales = [...sales].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    autoTable(doc, {
        startY: 25,
        head: [['Date', 'Product', 'Status', 'Qty', 'Amount']],
        body: sortedSales.map(s => [
            format(new Date(s.date), 'MMM d, yyyy HH:mm'),
            s.productName,
            isProductExempt(s.productName) ? 'Tax Exempt' : 'Taxable',
            s.quantity.toString(),
            `${currency}${s.revenue.toLocaleString()}`
        ]),
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [40, 40, 40] }
    });

    doc.addPage();
    doc.text("Appendix B: Detailed Expenses Log", 14, 20);

    // Sort expenses by date desc
    const sortedExpenses = [...expenses].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    autoTable(doc, {
        startY: 25,
        head: [['Date', 'Category', 'Description', 'Amount']],
        body: sortedExpenses.map(e => [
            format(new Date(e.date), 'MMM d, yyyy HH:mm'),
            e.category || 'Uncategorized',
            e.description,
            `${currency}${e.amount.toLocaleString()}`
        ]),
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [40, 40, 40] }
    });

    // Get Base64 without prefix
    const dataUri = doc.output('datauristring');
    const base64 = dataUri.split(',')[1];

    await writeAndShare(`Tax_Report_${period.replace(/ /g, '_')}_${Date.now()}.pdf`, base64);
};

export const shareTaxReportExcel = async (
    taxData: any,
    business: BusinessProfile,
    sales: Sale[],
    expenses: Expense[]
) => {
    const wb = XLSX.utils.book_new();
    const fmt = (num: number) => `N${num.toLocaleString()}`;

    // Sheet 1: Summary
    const summaryData = [
        ['DailyProfit Tax Insight Report'],
        ['Generated', new Date().toISOString()],
        ['Business', business.name],
        [],
        ['Metric', 'Amount', 'Notes'],
        ['Total Sales', fmt(taxData.totalRevenue), ''],
        ['Total Expenses', fmt(taxData.totalExpenses), ''],
        ['Net Profit', fmt(taxData.netProfit), ''],
        ['Taxable Sales', fmt(taxData.taxableSales), 'VAT applies here'],
        ['Exempt Sales', fmt(taxData.exemptSales), 'No VAT'],
        [],
        ['Estimated Taxes', '', ''],
        ['VAT (7.5%)', fmt(taxData.vatAmount), taxData.isVatExemptByTurnover ? 'Below Threshold' : ''],
        [taxData.taxType, fmt(taxData.incomeTaxAmount), 'Est. 5% of Profit'],
        ['TOTAL', fmt(taxData.vatAmount + taxData.incomeTaxAmount), '']
    ];
    const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, wsSummary, "Tax Estimate");

    // Sheet 2: Detailed Sales
    const sortedSales = [...sales].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    const salesData = [
        ['Date', 'Product', 'Tax Status', 'Quantity', 'Revenue', 'Cost', 'Profit'],
        ...sortedSales.map(s => [
            format(new Date(s.date), 'MMM d, yyyy HH:mm'),
            s.productName,
            isProductExempt(s.productName) ? 'Tax Exempt' : 'Taxable',
            s.quantity,
            s.revenue,
            s.cost,
            s.profit
        ])
    ];
    const wsSales = XLSX.utils.aoa_to_sheet(salesData);
    XLSX.utils.book_append_sheet(wb, wsSales, "Sales Detailed");

    // Sheet 3: Detailed Expenses
    const sortedExpenses = [...expenses].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    const expenseData = [
        ['Date', 'Category', 'Description', 'Amount'],
        ...sortedExpenses.map(e => [
            format(new Date(e.date), 'MMM d, yyyy HH:mm'),
            e.category || 'Uncategorized',
            e.description,
            e.amount
        ])
    ];
    const wsExpenses = XLSX.utils.aoa_to_sheet(expenseData);
    XLSX.utils.book_append_sheet(wb, wsExpenses, "Expenses Detailed");

    // Generate Base64
    const base64 = XLSX.write(wb, { bookType: 'xlsx', type: 'base64' });

    await writeAndShare(`Tax_Estimate_${business.name.replace(/ /g, '_')}.xlsx`, base64);
};
