require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '16.0'
inhibit_all_warnings!
use_frameworks!

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios', :inhibit_warnings => true
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios', :inhibit_warnings => true
  
  # Manual Plugin Linking with Warnings Silenced
  pod 'CodetrixStudioCapacitorGoogleAuth', :path => '../../node_modules/@codetrix-studio/capacitor-google-auth', :inhibit_warnings => true
  pod 'CapacitorMlkitBarcodeScanning', :path => '../../node_modules/@capacitor-mlkit/barcode-scanning', :inhibit_warnings => true
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications', :inhibit_warnings => true
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share', :inhibit_warnings => true
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar', :inhibit_warnings => true
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem', :inhibit_warnings => true
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app', :inhibit_warnings => true
  pod 'CapacitorCommunityAppleSignIn', :path => '../../node_modules/@capacitor-community/apple-sign-in', :inhibit_warnings => true
end

target 'App' do
  capacitor_pods
end

post_install do |installer|
  assertDeploymentTarget(installer)
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Fix for Xcode 15+ DT_TOOLCHAIN_DIR issue
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
      
      # Fix for User Script Sandboxing (Disable it for Pods)
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
